/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectId = IDL.Text;
export const CostItemId = IDL.Text;
export const DocumentId = IDL.Text;
export const Time = IDL.Int;
export const CostItem = IDL.Record({
  'id' : CostItemId,
  'status' : IDL.Text,
  'owner' : IDL.Principal,
  'dokumentId' : IDL.Opt(DocumentId),
  'projektId' : ProjectId,
  'betrag' : IDL.Float64,
  'kategorie' : IDL.Text,
  'beschreibung' : IDL.Text,
  'datum' : Time,
  'handwerker' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaId = IDL.Text;
export const MediaPositionUpdate = IDL.Record({
  'newPosition' : IDL.Int,
  'mediaId' : MediaId,
});
export const ContactId = IDL.Text;
export const UserType = IDL.Variant({
  'business' : IDL.Null,
  'privat' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'endDate' : IDL.Opt(Time),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'verantwortlicherKontakt' : IDL.Opt(ContactId),
  'kategorie' : IDL.Text,
  'kunde' : IDL.Text,
  'startDate' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'userType' : UserType,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const KostenUebersicht = IDL.Record({
  'offen' : IDL.Float64,
  'gesamt' : IDL.Float64,
  'bezahlt' : IDL.Float64,
});
export const Bereich = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'id' : DocumentId,
  'typ' : IDL.Text,
  'status' : IDL.Text,
  'bereich' : Bereich,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});
export const Media = IDL.Record({
  'id' : MediaId,
  'typ' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'kategorie' : IDL.Text,
  'position' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addKostenpunkt' : IDL.Func([ProjectId, CostItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateMediaPositions' : IDL.Func([IDL.Vec(MediaPositionUpdate)], [], []),
  'createProjekt' : IDL.Func(
      [
        ProjectId,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Text,
        IDL.Opt(ContactId),
        IDL.Vec(CostItem),
      ],
      [],
      [],
    ),
  'deleteKostenpunkt' : IDL.Func([ProjectId, CostItemId], [], []),
  'deleteProjekt' : IDL.Func([ProjectId], [], []),
  'deleteUserMedia' : IDL.Func([IDL.Text], [], []),
  'filterProjectsByUserType' : IDL.Func(
      [UserType],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getAllKostenpunkte' : IDL.Func([], [IDL.Vec(CostItem)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKostenUebersicht' : IDL.Func(
      [IDL.Opt(ProjectId)],
      [KostenUebersicht],
      ['query'],
    ),
  'getKostenpunkteByProjekt' : IDL.Func(
      [ProjectId],
      [IDL.Vec(CostItem)],
      ['query'],
    ),
  'getProjekt' : IDL.Func([ProjectId], [Project], ['query']),
  'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getUserMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateKostenpunkt' : IDL.Func([ProjectId, CostItemId, CostItem], [], []),
  'updateProjekt' : IDL.Func(
      [
        ProjectId,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Text,
        IDL.Opt(ContactId),
        IDL.Vec(CostItem),
      ],
      [],
      [],
    ),
  'uploadDocumentWithPDF' : IDL.Func(
      [IDL.Text, IDL.Text, Bereich, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'uploadMedia' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Vec(IDL.Text),
        ExternalBlob,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectId = IDL.Text;
  const CostItemId = IDL.Text;
  const DocumentId = IDL.Text;
  const Time = IDL.Int;
  const CostItem = IDL.Record({
    'id' : CostItemId,
    'status' : IDL.Text,
    'owner' : IDL.Principal,
    'dokumentId' : IDL.Opt(DocumentId),
    'projektId' : ProjectId,
    'betrag' : IDL.Float64,
    'kategorie' : IDL.Text,
    'beschreibung' : IDL.Text,
    'datum' : Time,
    'handwerker' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaId = IDL.Text;
  const MediaPositionUpdate = IDL.Record({
    'newPosition' : IDL.Int,
    'mediaId' : MediaId,
  });
  const ContactId = IDL.Text;
  const UserType = IDL.Variant({ 'business' : IDL.Null, 'privat' : IDL.Null });
  const Project = IDL.Record({
    'id' : ProjectId,
    'endDate' : IDL.Opt(Time),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'verantwortlicherKontakt' : IDL.Opt(ContactId),
    'kategorie' : IDL.Text,
    'kunde' : IDL.Text,
    'startDate' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'userType' : UserType,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const KostenUebersicht = IDL.Record({
    'offen' : IDL.Float64,
    'gesamt' : IDL.Float64,
    'bezahlt' : IDL.Float64,
  });
  const Bereich = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'id' : DocumentId,
    'typ' : IDL.Text,
    'status' : IDL.Text,
    'bereich' : Bereich,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
  });
  const Media = IDL.Record({
    'id' : MediaId,
    'typ' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'kategorie' : IDL.Text,
    'position' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addKostenpunkt' : IDL.Func([ProjectId, CostItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateMediaPositions' : IDL.Func(
        [IDL.Vec(MediaPositionUpdate)],
        [],
        [],
      ),
    'createProjekt' : IDL.Func(
        [
          ProjectId,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Text,
          IDL.Opt(ContactId),
          IDL.Vec(CostItem),
        ],
        [],
        [],
      ),
    'deleteKostenpunkt' : IDL.Func([ProjectId, CostItemId], [], []),
    'deleteProjekt' : IDL.Func([ProjectId], [], []),
    'deleteUserMedia' : IDL.Func([IDL.Text], [], []),
    'filterProjectsByUserType' : IDL.Func(
        [UserType],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getAllKostenpunkte' : IDL.Func([], [IDL.Vec(CostItem)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKostenUebersicht' : IDL.Func(
        [IDL.Opt(ProjectId)],
        [KostenUebersicht],
        ['query'],
      ),
    'getKostenpunkteByProjekt' : IDL.Func(
        [ProjectId],
        [IDL.Vec(CostItem)],
        ['query'],
      ),
    'getProjekt' : IDL.Func([ProjectId], [Project], ['query']),
    'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getUserMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateKostenpunkt' : IDL.Func([ProjectId, CostItemId, CostItem], [], []),
    'updateProjekt' : IDL.Func(
        [
          ProjectId,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Text,
          IDL.Opt(ContactId),
          IDL.Vec(CostItem),
        ],
        [],
        [],
      ),
    'uploadDocumentWithPDF' : IDL.Func(
        [IDL.Text, IDL.Text, Bereich, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'uploadMedia' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Vec(IDL.Text),
          ExternalBlob,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };