/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Bereich = string;
export type ContactId = string;
export interface CostItem {
  'id' : CostItemId,
  'status' : string,
  'owner' : Principal,
  'dokumentId' : [] | [DocumentId],
  'projektId' : ProjectId,
  'betrag' : number,
  'kategorie' : string,
  'beschreibung' : string,
  'datum' : Time,
  'handwerker' : [] | [string],
}
export type CostItemId = string;
export interface Document {
  'id' : DocumentId,
  'typ' : string,
  'status' : string,
  'bereich' : Bereich,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
}
export type DocumentId = string;
export type ExternalBlob = Uint8Array;
export interface KostenUebersicht {
  'offen' : number,
  'gesamt' : number,
  'bezahlt' : number,
}
export interface Media {
  'id' : MediaId,
  'typ' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'tags' : Array<string>,
  'kategorie' : string,
  'position' : bigint,
}
export type MediaId = string;
export interface MediaPositionUpdate {
  'newPosition' : bigint,
  'mediaId' : MediaId,
}
export interface Project {
  'id' : ProjectId,
  'endDate' : [] | [Time],
  'owner' : Principal,
  'name' : string,
  'color' : string,
  'verantwortlicherKontakt' : [] | [ContactId],
  'kategorie' : string,
  'kunde' : string,
  'startDate' : [] | [Time],
}
export type ProjectId = string;
export type Time = bigint;
export interface UserProfile {
  'userType' : UserType,
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'business' : null } |
  { 'privat' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addKostenpunkt' : ActorMethod<[ProjectId, CostItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateMediaPositions' : ActorMethod<
    [Array<MediaPositionUpdate>],
    undefined
  >,
  'createProjekt' : ActorMethod<
    [
      ProjectId,
      string,
      [] | [string],
      string,
      [] | [Time],
      [] | [Time],
      string,
      [] | [ContactId],
      Array<CostItem>,
    ],
    undefined
  >,
  'deleteKostenpunkt' : ActorMethod<[ProjectId, CostItemId], undefined>,
  'deleteProjekt' : ActorMethod<[ProjectId], undefined>,
  'deleteUserMedia' : ActorMethod<[string], undefined>,
  'filterProjectsByUserType' : ActorMethod<[UserType], Array<Project>>,
  'getAllKostenpunkte' : ActorMethod<[], Array<CostItem>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKostenUebersicht' : ActorMethod<[[] | [ProjectId]], KostenUebersicht>,
  'getKostenpunkteByProjekt' : ActorMethod<[ProjectId], Array<CostItem>>,
  'getProjekt' : ActorMethod<[ProjectId], Project>,
  'getUserDocuments' : ActorMethod<[], Array<Document>>,
  'getUserMedia' : ActorMethod<[], Array<Media>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateKostenpunkt' : ActorMethod<
    [ProjectId, CostItemId, CostItem],
    undefined
  >,
  'updateProjekt' : ActorMethod<
    [
      ProjectId,
      string,
      [] | [string],
      string,
      [] | [Time],
      [] | [Time],
      string,
      [] | [ContactId],
      Array<CostItem>,
    ],
    undefined
  >,
  'uploadDocumentWithPDF' : ActorMethod<
    [string, string, Bereich, string, string, ExternalBlob],
    undefined
  >,
  'uploadMedia' : ActorMethod<
    [string, string, string, string, bigint, Array<string>, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];