/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectId = IDL.Text;
export const CostItemId = IDL.Text;
export const DocumentId = IDL.Text;
export const Time = IDL.Int;
export const CostItem = IDL.Record({
  'id' : CostItemId,
  'status' : IDL.Text,
  'owner' : IDL.Principal,
  'dokumentId' : IDL.Opt(DocumentId),
  'projektId' : ProjectId,
  'betrag' : IDL.Float64,
  'kategorie' : IDL.Text,
  'beschreibung' : IDL.Text,
  'datum' : Time,
  'handwerker' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaId = IDL.Text;
export const MediaPositionUpdate = IDL.Record({
  'newPosition' : IDL.Int,
  'mediaId' : MediaId,
});
export const ContactId = IDL.Text;
export const TaskId = IDL.Text;
export const LinkId = IDL.Text;
export const Bereich = IDL.Text;
export const UserType = IDL.Variant({
  'business' : IDL.Null,
  'privat' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'endDate' : IDL.Opt(Time),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'verantwortlicherKontakt' : IDL.Opt(ContactId),
  'kategorie' : IDL.Text,
  'kunde' : IDL.Text,
  'startDate' : IDL.Opt(Time),
});
export const Contact = IDL.Record({
  'id' : ContactId,
  'firma' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'notizen' : IDL.Text,
  'verknuepfteTasks' : IDL.Vec(TaskId),
  'email' : IDL.Text,
  'verknuepfteDokumente' : IDL.Vec(DocumentId),
  'telefon' : IDL.Text,
  'rolle' : IDL.Text,
});
export const HelpfulLink = IDL.Record({
  'id' : LinkId,
  'url' : IDL.Text,
  'titel' : IDL.Text,
  'owner' : IDL.Principal,
  'logoUrl' : IDL.Text,
  'kategorie' : IDL.Text,
  'beschreibung' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'status' : IDL.Text,
  'titel' : IDL.Text,
  'bereich' : Bereich,
  'owner' : IDL.Principal,
  'verantwortlicherKontakt' : IDL.Opt(ContactId),
  'projectId' : IDL.Opt(ProjectId),
  'kategorie' : IDL.Text,
  'faelligkeit' : Time,
  'dringlichkeit' : IDL.Nat,
  'beschreibung' : IDL.Text,
  'gewerke' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userType' : UserType,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const KostenUebersicht = IDL.Record({
  'offen' : IDL.Float64,
  'gesamt' : IDL.Float64,
  'bezahlt' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'id' : DocumentId,
  'typ' : IDL.Text,
  'status' : IDL.Text,
  'bereich' : Bereich,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});
export const Media = IDL.Record({
  'id' : MediaId,
  'typ' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'kategorie' : IDL.Text,
  'position' : IDL.Int,
});
export const MediaUpdate = IDL.Record({
  'typ' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'kategorie' : IDL.Opt(IDL.Text),
  'position' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addKostenpunkt' : IDL.Func([ProjectId, CostItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateMediaPositions' : IDL.Func([IDL.Vec(MediaPositionUpdate)], [], []),
  'createContact' : IDL.Func(
      [
        ContactId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(TaskId),
        IDL.Vec(DocumentId),
      ],
      [],
      [],
    ),
  'createHelpfulLink' : IDL.Func(
      [LinkId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createProjekt' : IDL.Func(
      [
        ProjectId,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Text,
        IDL.Opt(ContactId),
        IDL.Vec(CostItem),
      ],
      [],
      [],
    ),
  'createTask' : IDL.Func(
      [
        TaskId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Bereich,
        Time,
        IDL.Text,
        IDL.Opt(ContactId),
        IDL.Opt(ProjectId),
      ],
      [],
      [],
    ),
  'deleteContact' : IDL.Func([ContactId], [], []),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'deleteHelpfulLink' : IDL.Func([LinkId], [], []),
  'deleteKostenpunkt' : IDL.Func([ProjectId, CostItemId], [], []),
  'deleteProjekt' : IDL.Func([ProjectId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'deleteUserMedia' : IDL.Func([IDL.Text], [], []),
  'filterProjectsByUserType' : IDL.Func(
      [UserType],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllHelpfulLinks' : IDL.Func([], [IDL.Vec(HelpfulLink)], ['query']),
  'getAllKostenpunkte' : IDL.Func([], [IDL.Vec(CostItem)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([ContactId], [Contact], ['query']),
  'getHelpfulLink' : IDL.Func([LinkId], [HelpfulLink], ['query']),
  'getKostenUebersicht' : IDL.Func(
      [IDL.Opt(ProjectId)],
      [KostenUebersicht],
      ['query'],
    ),
  'getKostenpunkteByProjekt' : IDL.Func(
      [ProjectId],
      [IDL.Vec(CostItem)],
      ['query'],
    ),
  'getProjekt' : IDL.Func([ProjectId], [Project], ['query']),
  'getTask' : IDL.Func([TaskId], [Task], ['query']),
  'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getUserMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContact' : IDL.Func(
      [
        ContactId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(TaskId),
        IDL.Vec(DocumentId),
      ],
      [],
      [],
    ),
  'updateHelpfulLink' : IDL.Func(
      [LinkId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateKostenpunkt' : IDL.Func([ProjectId, CostItemId, CostItem], [], []),
  'updateMedia' : IDL.Func([IDL.Text, MediaUpdate], [], []),
  'updateProjekt' : IDL.Func(
      [
        ProjectId,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Text,
        IDL.Opt(ContactId),
        IDL.Vec(CostItem),
      ],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [
        TaskId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Bereich,
        Time,
        IDL.Text,
        IDL.Opt(ContactId),
        IDL.Opt(ProjectId),
      ],
      [],
      [],
    ),
  'uploadDocumentWithPDF' : IDL.Func(
      [IDL.Text, IDL.Text, Bereich, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'uploadMedia' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Vec(IDL.Text),
        ExternalBlob,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectId = IDL.Text;
  const CostItemId = IDL.Text;
  const DocumentId = IDL.Text;
  const Time = IDL.Int;
  const CostItem = IDL.Record({
    'id' : CostItemId,
    'status' : IDL.Text,
    'owner' : IDL.Principal,
    'dokumentId' : IDL.Opt(DocumentId),
    'projektId' : ProjectId,
    'betrag' : IDL.Float64,
    'kategorie' : IDL.Text,
    'beschreibung' : IDL.Text,
    'datum' : Time,
    'handwerker' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaId = IDL.Text;
  const MediaPositionUpdate = IDL.Record({
    'newPosition' : IDL.Int,
    'mediaId' : MediaId,
  });
  const ContactId = IDL.Text;
  const TaskId = IDL.Text;
  const LinkId = IDL.Text;
  const Bereich = IDL.Text;
  const UserType = IDL.Variant({ 'business' : IDL.Null, 'privat' : IDL.Null });
  const Project = IDL.Record({
    'id' : ProjectId,
    'endDate' : IDL.Opt(Time),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'verantwortlicherKontakt' : IDL.Opt(ContactId),
    'kategorie' : IDL.Text,
    'kunde' : IDL.Text,
    'startDate' : IDL.Opt(Time),
  });
  const Contact = IDL.Record({
    'id' : ContactId,
    'firma' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'notizen' : IDL.Text,
    'verknuepfteTasks' : IDL.Vec(TaskId),
    'email' : IDL.Text,
    'verknuepfteDokumente' : IDL.Vec(DocumentId),
    'telefon' : IDL.Text,
    'rolle' : IDL.Text,
  });
  const HelpfulLink = IDL.Record({
    'id' : LinkId,
    'url' : IDL.Text,
    'titel' : IDL.Text,
    'owner' : IDL.Principal,
    'logoUrl' : IDL.Text,
    'kategorie' : IDL.Text,
    'beschreibung' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'status' : IDL.Text,
    'titel' : IDL.Text,
    'bereich' : Bereich,
    'owner' : IDL.Principal,
    'verantwortlicherKontakt' : IDL.Opt(ContactId),
    'projectId' : IDL.Opt(ProjectId),
    'kategorie' : IDL.Text,
    'faelligkeit' : Time,
    'dringlichkeit' : IDL.Nat,
    'beschreibung' : IDL.Text,
    'gewerke' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userType' : UserType,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const KostenUebersicht = IDL.Record({
    'offen' : IDL.Float64,
    'gesamt' : IDL.Float64,
    'bezahlt' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'id' : DocumentId,
    'typ' : IDL.Text,
    'status' : IDL.Text,
    'bereich' : Bereich,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
  });
  const Media = IDL.Record({
    'id' : MediaId,
    'typ' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'kategorie' : IDL.Text,
    'position' : IDL.Int,
  });
  const MediaUpdate = IDL.Record({
    'typ' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'kategorie' : IDL.Opt(IDL.Text),
    'position' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addKostenpunkt' : IDL.Func([ProjectId, CostItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateMediaPositions' : IDL.Func(
        [IDL.Vec(MediaPositionUpdate)],
        [],
        [],
      ),
    'createContact' : IDL.Func(
        [
          ContactId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(TaskId),
          IDL.Vec(DocumentId),
        ],
        [],
        [],
      ),
    'createHelpfulLink' : IDL.Func(
        [LinkId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createProjekt' : IDL.Func(
        [
          ProjectId,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Text,
          IDL.Opt(ContactId),
          IDL.Vec(CostItem),
        ],
        [],
        [],
      ),
    'createTask' : IDL.Func(
        [
          TaskId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Bereich,
          Time,
          IDL.Text,
          IDL.Opt(ContactId),
          IDL.Opt(ProjectId),
        ],
        [],
        [],
      ),
    'deleteContact' : IDL.Func([ContactId], [], []),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'deleteHelpfulLink' : IDL.Func([LinkId], [], []),
    'deleteKostenpunkt' : IDL.Func([ProjectId, CostItemId], [], []),
    'deleteProjekt' : IDL.Func([ProjectId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'deleteUserMedia' : IDL.Func([IDL.Text], [], []),
    'filterProjectsByUserType' : IDL.Func(
        [UserType],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllHelpfulLinks' : IDL.Func([], [IDL.Vec(HelpfulLink)], ['query']),
    'getAllKostenpunkte' : IDL.Func([], [IDL.Vec(CostItem)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([ContactId], [Contact], ['query']),
    'getHelpfulLink' : IDL.Func([LinkId], [HelpfulLink], ['query']),
    'getKostenUebersicht' : IDL.Func(
        [IDL.Opt(ProjectId)],
        [KostenUebersicht],
        ['query'],
      ),
    'getKostenpunkteByProjekt' : IDL.Func(
        [ProjectId],
        [IDL.Vec(CostItem)],
        ['query'],
      ),
    'getProjekt' : IDL.Func([ProjectId], [Project], ['query']),
    'getTask' : IDL.Func([TaskId], [Task], ['query']),
    'getUserDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getUserMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContact' : IDL.Func(
        [
          ContactId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(TaskId),
          IDL.Vec(DocumentId),
        ],
        [],
        [],
      ),
    'updateHelpfulLink' : IDL.Func(
        [LinkId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateKostenpunkt' : IDL.Func([ProjectId, CostItemId, CostItem], [], []),
    'updateMedia' : IDL.Func([IDL.Text, MediaUpdate], [], []),
    'updateProjekt' : IDL.Func(
        [
          ProjectId,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Text,
          IDL.Opt(ContactId),
          IDL.Vec(CostItem),
        ],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [
          TaskId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Bereich,
          Time,
          IDL.Text,
          IDL.Opt(ContactId),
          IDL.Opt(ProjectId),
        ],
        [],
        [],
      ),
    'uploadDocumentWithPDF' : IDL.Func(
        [IDL.Text, IDL.Text, Bereich, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'uploadMedia' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Vec(IDL.Text),
          ExternalBlob,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };